# Generated by Django 4.1.3 on 2023-02-15 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('phone_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
                ('acess_type', models.CharField(choices=[('A', 'Admin'), ('E', 'Employee')], max_length=20)),
                ('employee_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('employee_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.designation')),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='leave_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=100)),
                ('max_leaves', models.IntegerField()),
                ('carry_forword', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('1', 'Approved'), ('2', 'Rejected')], max_length=20, null=True)),
                ('A_R_date', models.DateField(blank=True, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leave', to='employee.employee')),
                ('leave_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leave_type')),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_in', models.TimeField()),
                ('punch_out', models.TimeField(null=True)),
                ('date', models.DateField()),
                ('duration', models.TimeField(blank=True, null=True)),
                ('employee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendence', to='employee.employee')),
            ],
        ),
    ]
